Style/StringLiterals:
  EnforcedStyle: double_quotes
Metrics/MethodLength:
  Max: 12
Metrics/LineLength:
  Max: 100
  AllowHeredoc: true
  AllowURI: true
Documentation:
  Enabled: false
Metrics/AbcSize:
  Max: 18
